entradas:
    path:     /
    defaults: { _controller: "BlogBundle:Entradas:index" }

entradas_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Entradas:show" }

entradas_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Entradas:new" }

entradas_create:
    path:     /create
    defaults: { _controller: "BlogBundle:Entradas:create" }
    requirements: { _method: post }

entradas_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Entradas:edit" }

entradas_update:
    path:     /{id}/update
    defaults: { _controller: "BlogBundle:Entradas:update" }
    requirements: { _method: post|put }

entradas_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Entradas:delete" }
    requirements: { _method: post|delete }
